### ISSUE TITLE
Parallelism should be based off numcpu not numgoroutinr

### ISSUE THREAD

**Issue by witchard** [gershwinlabs/go-overview#4]
This code: https://github.com/gershwinlabs/go-overview/blob/4f801b76845ee2fb7b62888b079c17a500fb9b3c/solutions/cmd/ex4/main.go#L15 should use numcpu

See docs https://godoc.org/runtime#NumCPU

**Comment by billallen256** [comment]
Indeed.  I'm doing some tidy up, so I'll fix it.
